name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: .next
          token: ${{ secrets.STORYBOOK_ID }}

      - name: Debug
        if: failure()
        run: |
          echo "Build and deploy failed."
          echo "Exit code: ${{ job.status }}"
          echo "Job logs:"
          cat ${{ github.workspace }}/build-and-deploy.log || echo "No logs found."

      - name: Save deployment status
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
        run: echo "JOB_STATUS=${JOB_STATUS}" >> $GITHUB_ENV
